#!/bin/bash
ssh -t russell "mongodump --gzip --db sssm --archive=sssm-db.gz"
scp russell:sssm-db.gz /tmp/
mongo russell --eval "db.dropDatabase()"
mongorestore --gzip --archive=/tmp/sssm-db.gz
rm -fr /tmp/sssm-db.gz
